name: CI

on:
  push:
    branches:
    - master
    - gh-pages

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: helm_tests
      run: sh .circleci/helm_test.sh
